/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doc2html;

import org.junit.Test;
import static org.junit.Assert.*;

public class Doc2HTMLTest {
    @Test public void testDoc2HTMLHasAGreeting() {
        assertNull("app should have a documentToString", Doc2HTML.documentToString(null));
    }
}
